# -*- coding: utf-8 -*-
"""CIFAR 10 Image Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QE9oHYmw-Rz5ep8DrA-tPX1WIUl_uiFQ
"""

import tensorflow as tf  
 
# Display the version
print(tf.__version__)    
 
# other imports
import numpy as np
import matplotlib.pyplot as plt

from tensorflow.keras.layers import Input, Conv2D, Dense, Flatten, Dropout
from tensorflow.keras.layers import GlobalMaxPooling2D, MaxPooling2D
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.models import Model,Sequential

cifar10 = tf.keras.datasets.cifar10

(train_input,train_label),(test_input,test_label) = cifar10.load_data()

print(train_input.shape,train_label.shape)
print(test_input.shape,test_label.shape)

"""## Labels & Categories

0.	airplane
1.	automobile
2.	bird
3.	cat
4.	deer
5.	dog
6.	frog
7.	horse
8.	ship
9.	truck
"""

plt.imshow(train_input[90])
plt.show()
print(train_label[90])

train_input, test_input = train_input / 255.0, test_input / 255.0
train_label, test_label = train_label.flatten(), test_label.flatten()

print(train_input[1])

plt.imshow(train_input[100])
plt.show()
print(train_label[90])

model = Sequential([
    Conv2D(32,(3,3),activation="relu",input_shape=(32,32,3)),
    MaxPooling2D((2,2)),
    Conv2D(64,(3,3),activation="relu"),
    MaxPooling2D((2,2)),
    Conv2D(64,(3,3),activation="relu"),
    Flatten(),
    Dense(64,activation="relu"),
    Dense(10)
])

model.summary()

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(train_input,train_label,epochs=10,validation_data=(test_input,test_label))

plt.plot(history.history['accuracy'], label='accuracy')
plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.ylim([0.5, 1])
plt.legend(loc='lower right')

test_loss, test_acc = model.evaluate(test_input,  test_label, verbose=2)
print(test_acc)