# -*- coding: utf-8 -*-
"""Edge Detections.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vEwmRoKHYA40w8x5SoAxSie4tIsI-AS8

# Edge Detections
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt

def show_im(image):
  plt.imshow(image)
  plt.show()

image = cv2.imread('gugu.jpg')
image = cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
show_im(image)

"""### Soble Edge Detection"""

img_gray = cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
img_blur = cv2.GaussianBlur(src=img_gray,ksize=(5,5),sigmaX=0)
show_im(img_blur)

sobelx = cv2.Sobel(src=img_blur, ddepth=cv2.CV_64F, dx=1, dy=0, ksize=5) # Sobel Edge Detection on the X axis
sobely = cv2.Sobel(src=img_blur, ddepth=cv2.CV_64F, dx=0, dy=1, ksize=5) # Sobel Edge Detection on the Y axis
sobelxy = cv2.Sobel(src=img_blur, ddepth=cv2.CV_64F, dx=1, dy=1, ksize=5)

show_im(sobelx)
show_im(sobely)
show_im(sobelxy)

"""## Canny Edge Detection"""

show_im(img_blur)
canny_img = cv2.Canny(image=img_blur, threshold1=100, threshold2=200) 
show_im(canny_img)