# -*- coding: utf-8 -*-
"""Filters.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tgt1c3rm7d8h00IsgErIeg81Aj96KAXw

# Filters & Edge Detections
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt

def show_img(img):
  plt.imshow(img)
  plt.show()

image = cv2.imread("gugu.jpg",1)
image = cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
print(image.shape)

"""## Blurring the Image"""

kernel = np.ones((5,5),np.float32)/25
kernel2 = np.ones((5,5),np.float32)/5
kernel3 = np.ones((5,5),np.float32)/15
blur_img = cv2.filter2D(src=image,kernel=kernel,ddepth=-1)
blur_img2 = cv2.filter2D(src=image,kernel=kernel2,ddepth=-1)
blur_img3 = cv2.filter2D(src=image,kernel=kernel3,ddepth=-1)

show_img(image)
show_img(blur_img)
show_img(blur_img2)
show_img(blur_img3)

"""## Edge Detection Filter"""

kernel_ed = np.array([
    [-1, -1, -1],
    [-1, 8, -1],
    [-1, -1, -1]
])

ed_img = cv2.filter2D(src=image,kernel=kernel_ed,ddepth=-1)
show_img(image)
show_img(ed_img)

"""## Gaussian Blurring"""

gaussian_blur = cv2.GaussianBlur(src=image,ksize=(5,5),sigmaX=0,sigmaY=0)
gaussian_blur2 = cv2.GaussianBlur(src=image,ksize=(7,7),sigmaX=0,sigmaY=0)
show_img(image)
show_img(gaussian_blur)
show_img(gaussian_blur2)

"""## Median Blur"""

median_blur = cv2.medianBlur(src=image,ksize=5)
median_blur2 = cv2.medianBlur(src=image,ksize=7)
show_img(image)
show_img(median_blur)
show_img(median_blur2)